"""empty message

Revision ID: 7e71d4b1b020
Revises: 
Create Date: 2022-03-18 23:51:14.803256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e71d4b1b020'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('birth_year', sa.String(length=120), nullable=True),
    sa.Column('eye_color', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=120), nullable=True),
    sa.Column('hair_color', sa.String(length=120), nullable=True),
    sa.Column('height', sa.String(length=120), nullable=True),
    sa.Column('mass', sa.String(length=120), nullable=True),
    sa.Column('skin_color', sa.String(length=120), nullable=True),
    sa.Column('homeworld', sa.String(length=120), nullable=True),
    sa.Column('films', sa.String(length=120), nullable=True),
    sa.Column('species', sa.String(length=120), nullable=True),
    sa.Column('starships', sa.String(length=120), nullable=True),
    sa.Column('vehicles', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('birth_year'),
    sa.UniqueConstraint('eye_color'),
    sa.UniqueConstraint('films'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('hair_color'),
    sa.UniqueConstraint('height'),
    sa.UniqueConstraint('homeworld'),
    sa.UniqueConstraint('mass'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('skin_color'),
    sa.UniqueConstraint('species'),
    sa.UniqueConstraint('starships'),
    sa.UniqueConstraint('vehicles')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('diameter', sa.String(length=120), nullable=True),
    sa.Column('rotation_period', sa.String(length=120), nullable=True),
    sa.Column('orbital_period', sa.String(length=120), nullable=True),
    sa.Column('gravity', sa.String(length=120), nullable=True),
    sa.Column('population', sa.String(length=120), nullable=True),
    sa.Column('climate', sa.String(length=120), nullable=True),
    sa.Column('terrain', sa.String(length=120), nullable=True),
    sa.Column('surface_water', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('climate'),
    sa.UniqueConstraint('diameter'),
    sa.UniqueConstraint('gravity'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('orbital_period'),
    sa.UniqueConstraint('population'),
    sa.UniqueConstraint('rotation_period'),
    sa.UniqueConstraint('surface_water'),
    sa.UniqueConstraint('terrain')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('vehicles', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=120), nullable=True),
    sa.Column('cost_in_credits', sa.String(length=120), nullable=True),
    sa.Column('crew', sa.String(length=120), nullable=True),
    sa.Column('passengers', sa.String(length=120), nullable=True),
    sa.Column('max_atmosphering_speed', sa.String(length=120), nullable=True),
    sa.Column('cargo_capacity', sa.String(length=120), nullable=True),
    sa.Column('consumables', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cargo_capacity'),
    sa.UniqueConstraint('consumables'),
    sa.UniqueConstraint('cost_in_credits'),
    sa.UniqueConstraint('crew'),
    sa.UniqueConstraint('length'),
    sa.UniqueConstraint('manufacturer'),
    sa.UniqueConstraint('max_atmosphering_speed'),
    sa.UniqueConstraint('model'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('passengers'),
    sa.UniqueConstraint('vehicles')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('user')
    op.drop_table('planet')
    op.drop_table('person')
    # ### end Alembic commands ###
